version: "3.7"
services:
  postgres:
    image: postgres:13.2
    container_name: postgres
    environment:
      POSTGRES_USER: uphold
      POSTGRES_PASSWORD: uphold
      POSTGRES_DB: uphold
    ports: 
      - '5432:5432'
    volumes:
      - bot-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U uphold -d uphold
      interval: 10s
      timeout: 3s
      retries: 3

  bot:
    container_name: bot
    build:
      context: .
    environment:
      APP_ENV: production
      DB_USER: uphold
      DB_PASSWORD: uphold
      DB_HOST: postgres
      DB_DATABASE: uphold
      BASE_URL: https://api-sandbox.uphold.com
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
        
volumes:
  bot-db: